export const LoaderConfig = {
    Background: "src/sprites/Background.jpg",
    reelBg: "src/sprites/reelBg.png",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",      
    balancePanel :  "/src/sprites/PanelBalance.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png", 
    settingHeading: "src/sprites/SettingPopupBg.png",


    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    messagePopup: "src/sprites/messagePopup.png",
    
    disconnectClose: "src/sprites/CloseButton.png",
    toggleOff: "src/sprites/toggleOff.png",
    toggleOn: "src/sprites/toggleOn.png",
    SoundToggleBg: "src/sprites/SoundToggleBg.png",

    headingImage: "src/sprites/PayTable.png",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MinorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    payLines: "src/sprites/PayLines.png",
    payLinesHeading: "src/sprites/PayLinesHeading.png",
    bigWinPopup:"src/sprites/bigWinPopup.png",
    hugeWinPopup: "src/sprites/hugeWinPopup.png",
    megaWinPopup: "src/sprites/megaWinPopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",

    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",

    slots0_0 : "/src/sprites/Symbols/icon1/Pickaxe1.png",
    slots0_1 : "/src/sprites/Symbols/icon1/Pickaxe2.png",
    slots0_2 : "/src/sprites/Symbols/icon1/Pickaxe3.png",
    slots0_3 : "/src/sprites/Symbols/icon1/Pickaxe4.png",
    slots0_4 : "/src/sprites/Symbols/icon1/Pickaxe5.png",
    slots0_5 : "/src/sprites/Symbols/icon1/Pickaxe6.png",
    slots0_6 : "/src/sprites/Symbols/icon1/Pickaxe7.png",
    slots0_7 : "/src/sprites/Symbols/icon1/Pickaxe8.png",
    slots0_8 : "/src/sprites/Symbols/icon1/Pickaxe9.png",
    slots0_9 : "/src/sprites/Symbols/icon1/Pickaxe10.png",
    slots0_10 : "/src/sprites/Symbols/icon1/Pickaxe11.png",
    slots0_11 : "/src/sprites/Symbols/icon1/Pickaxe12.png",
    slots0_12 : "/src/sprites/Symbols/icon1/Pickaxe13.png",
    slots0_13 : "/src/sprites/Symbols/icon1/Pickaxe14.png",
    slots0_14 : "/src/sprites/Symbols/icon1/Pickaxe15.png",
    slots0_15 : "/src/sprites/Symbols/icon1/Pickaxe16.png",


    slots1_0 : "/src/sprites/Symbols/icon2/Lantern1.png",
    slots1_1:  "/src/sprites/Symbols/icon2/Lantern2.png",
    slots1_2:  "/src/sprites/Symbols/icon2/Lantern3.png",
    slots1_3:  "/src/sprites/Symbols/icon2/Lantern4.png",
    slots1_4:  "/src/sprites/Symbols/icon2/Lantern5.png",
    slots1_5:  "/src/sprites/Symbols/icon2/Lantern6.png",
    slots1_6:  "/src/sprites/Symbols/icon2/Lantern7.png",
    slots1_7 : "/src/sprites/Symbols/icon2/Lantern8.png",
    slots1_8 : "/src/sprites/Symbols/icon2/Lantern9.png",
    slots1_9 : "/src/sprites/Symbols/icon2/Lantern10.png",
    slots1_10 : "/src/sprites/Symbols/icon2/Lantern11.png",
    slots1_11 : "/src/sprites/Symbols/icon2/Lantern12.png",
    slots1_12 : "/src/sprites/Symbols/icon2/Lantern13.png",
    slots1_13 : "/src/sprites/Symbols/icon2/Lantern14.png",
    slots1_14 : "/src/sprites/Symbols/icon2/Lantern15.png",
    slots1_15 : "/src/sprites/Symbols/icon2/Lantern16.png",

    slots2_0 :  "/src/sprites/Symbols/icon3/Gold1.png",
    slots2_1 : "/src/sprites/Symbols/icon3/Gold2.png",
    slots2_2 : "/src/sprites/Symbols/icon3/Gold3.png",
    slots2_3 : "/src/sprites/Symbols/icon3/Gold4.png",
    slots2_4 : "/src/sprites/Symbols/icon3/Gold5.png",
    slots2_5 : "/src/sprites/Symbols/icon3/Gold6.png",
    slots2_6 : "/src/sprites/Symbols/icon3/Gold7.png",
    slots2_7 : "/src/sprites/Symbols/icon3/Gold8.png",
    slots2_8 : "/src/sprites/Symbols/icon3/Gold9.png",
    slots2_9 : "/src/sprites/Symbols/icon3/Gold10.png",
    slots2_10 : "/src/sprites/Symbols/icon3/Gold11.png",
    slots2_11 : "/src/sprites/Symbols/icon3/Gold12.png",
    slots2_12 : "/src/sprites/Symbols/icon3/Gold13.png",
    slots2_13 : "/src/sprites/Symbols/icon3/Gold14.png",
    slots2_14 : "/src/sprites/Symbols/icon3/Gold15.png",
    slots2_15 : "/src/sprites/Symbols/icon3/Gold16.png",


    slots3_0 :  "/src/sprites/Symbols/icon4/Minecart1.png",
    slots3_1 :  "/src/sprites/Symbols/icon4/Minecart2.png",
    slots3_2 :  "/src/sprites/Symbols/icon4/Minecart3.png",
    slots3_3 :  "/src/sprites/Symbols/icon4/Minecart4.png",
    slots3_4 :  "/src/sprites/Symbols/icon4/Minecart5.png",
    slots3_5 :  "/src/sprites/Symbols/icon4/Minecart6.png",
    slots3_6 :  "/src/sprites/Symbols/icon4/Minecart7.png",
    slots3_7 :  "/src/sprites/Symbols/icon4/Minecart8.png",
    slots3_8 :  "/src/sprites/Symbols/icon4/Minecart9.png",
    slots3_9 :  "/src/sprites/Symbols/icon4/Minecart10.png",
    slots3_10 :  "/src/sprites/Symbols/icon4/Minecart11.png",
    slots3_11 :  "/src/sprites/Symbols/icon4/Minecart12.png",
    slots3_12 :  "/src/sprites/Symbols/icon4/Minecart13.png",
    slots3_13 :  "/src/sprites/Symbols/icon4/Minecart14.png",
    slots3_14 :  "/src/sprites/Symbols/icon4/Minecart15.png",
    slots3_15 :  "/src/sprites/Symbols/icon4/Minecart16.png",

    slots4_0 :  "/src/sprites/Symbols/icon5/101.png",
    slots4_1 :  "/src/sprites/Symbols/icon5/102.png",
    slots4_2 :  "/src/sprites/Symbols/icon5/103.png",
    slots4_3 :  "/src/sprites/Symbols/icon5/104.png",
    slots4_4 :  "/src/sprites/Symbols/icon5/105.png",
    slots4_5 :  "/src/sprites/Symbols/icon5/106.png",
    slots4_6 :  "/src/sprites/Symbols/icon5/107.png",
    slots4_7 :  "/src/sprites/Symbols/icon5/108.png",
    slots4_8 :  "/src/sprites/Symbols/icon5/109.png",
    slots4_9 :  "/src/sprites/Symbols/icon5/1010.png",
    slots4_10 :  "/src/sprites/Symbols/icon5/1011.png",
    slots4_11 :  "/src/sprites/Symbols/icon5/1012.png",
    slots4_12 :  "/src/sprites/Symbols/icon5/1013.png",
    slots4_13 :  "/src/sprites/Symbols/icon5/1014.png",
    slots4_14 :  "/src/sprites/Symbols/icon5/1015.png",
    slots4_15 :  "/src/sprites/Symbols/icon5/1016.png",

    slots5_0 :  "/src/sprites/Symbols/icon6/J1.png",
    slots5_1 :  "/src/sprites/Symbols/icon6/J2.png",
    slots5_2 :  "/src/sprites/Symbols/icon6/J3.png",
    slots5_3 :  "/src/sprites/Symbols/icon6/J4.png",
    slots5_4 :  "/src/sprites/Symbols/icon6/J5.png",
    slots5_5 :  "/src/sprites/Symbols/icon6/J6.png",
    slots5_6 :  "/src/sprites/Symbols/icon6/J7.png",
    slots5_7 :  "/src/sprites/Symbols/icon6/J8.png",
    slots5_8 :  "/src/sprites/Symbols/icon6/J9.png",
    slots5_9 :  "/src/sprites/Symbols/icon6/J10.png",
    slots5_10 :  "/src/sprites/Symbols/icon6/J11.png",
    slots5_11 :  "/src/sprites/Symbols/icon6/J12.png",
    slots5_12 :  "/src/sprites/Symbols/icon6/J13.png",
    slots5_13 :  "/src/sprites/Symbols/icon6/J14.png",
    slots5_14 :  "/src/sprites/Symbols/icon6/J15.png",
    slots5_15 :  "/src/sprites/Symbols/icon6/J16.png",

    slots6_0 :  "/src/sprites/Symbols/icon7/Q1.png",
    slots6_1 :  "/src/sprites/Symbols/icon7/Q2.png",
    slots6_2 :  "/src/sprites/Symbols/icon7/Q3.png",
    slots6_3 :  "/src/sprites/Symbols/icon7/Q4.png",
    slots6_4 :  "/src/sprites/Symbols/icon7/Q5.png",
    slots6_5 :  "/src/sprites/Symbols/icon7/Q6.png",
    slots6_6 :  "/src/sprites/Symbols/icon7/Q7.png",
    slots6_7 :  "/src/sprites/Symbols/icon7/Q8.png",
    slots6_8 :  "/src/sprites/Symbols/icon7/Q9.png",
    slots6_9 :  "/src/sprites/Symbols/icon7/Q10.png",
    slots6_10 :  "/src/sprites/Symbols/icon7/Q11.png",
    slots6_11 :  "/src/sprites/Symbols/icon7/Q12.png",
    slots6_12 :  "/src/sprites/Symbols/icon7/Q13.png",
    slots6_13 :  "/src/sprites/Symbols/icon7/Q14.png",
    slots6_14 :  "/src/sprites/Symbols/icon7/Q15.png",
    slots6_15 :  "/src/sprites/Symbols/icon7/Q16.png",


    slots7_0 :  "/src/sprites/Symbols/icon8/K1.png",
    slots7_1 :  "/src/sprites/Symbols/icon8/K2.png",
    slots7_2 :  "/src/sprites/Symbols/icon8/K3.png",
    slots7_3 :  "/src/sprites/Symbols/icon8/K4.png",
    slots7_4 :  "/src/sprites/Symbols/icon8/K5.png",
    slots7_5 :  "/src/sprites/Symbols/icon8/K6.png",
    slots7_6 :  "/src/sprites/Symbols/icon8/K7.png",
    slots7_7 :  "/src/sprites/Symbols/icon8/K8.png",
    slots7_8 :  "/src/sprites/Symbols/icon8/K9.png",
    slots7_9 :  "/src/sprites/Symbols/icon8/K10.png",
    slots7_10 :  "/src/sprites/Symbols/icon8/K11.png",
    slots7_11 :  "/src/sprites/Symbols/icon8/K12.png",
    slots7_12 :  "/src/sprites/Symbols/icon8/K13.png",
    slots7_13 :  "/src/sprites/Symbols/icon8/K14.png",
    slots7_14 :  "/src/sprites/Symbols/icon8/K15.png",
    slots7_15 :  "/src/sprites/Symbols/icon8/K16.png",

    slots8_0 : "/src/sprites/Symbols/icon9/A1.png",
    slots8_1 : "/src/sprites/Symbols/icon9/A2.png",
    slots8_2 : "/src/sprites/Symbols/icon9/A3.png",
    slots8_3 : "/src/sprites/Symbols/icon9/A4.png",
    slots8_4 : "/src/sprites/Symbols/icon9/A5.png",
    slots8_5 : "/src/sprites/Symbols/icon9/A6.png",
    slots8_6 : "/src/sprites/Symbols/icon9/A7.png",
    slots8_7 : "/src/sprites/Symbols/icon9/A8.png",
    slots8_8 : "/src/sprites/Symbols/icon9/A9.png",
    slots8_9 : "/src/sprites/Symbols/icon9/A10.png",
    slots8_10 : "/src/sprites/Symbols/icon9/A11.png",
    slots8_11 : "/src/sprites/Symbols/icon9/A12.png",
    slots8_12 : "/src/sprites/Symbols/icon9/A13.png",
    slots8_13 : "/src/sprites/Symbols/icon9/A14.png",
    slots8_14 : "/src/sprites/Symbols/icon9/A15.png",
    slots8_15 : "/src/sprites/Symbols/icon9/A16.png",

    slots9_0 : "/src/sprites/Symbols/icon10/wild1.png",
    slots9_1 : "/src/sprites/Symbols/icon10/wild2.png",
    slots9_2 : "/src/sprites/Symbols/icon10/wild3.png",
    slots9_3 : "/src/sprites/Symbols/icon10/wild4.png",
    slots9_4 : "/src/sprites/Symbols/icon10/wild5.png",
    slots9_5 : "/src/sprites/Symbols/icon10/wild6.png",
    slots9_6 : "/src/sprites/Symbols/icon10/wild7.png",
    slots9_7 : "/src/sprites/Symbols/icon10/wild8.png",
    slots9_8 : "/src/sprites/Symbols/icon10/wild9.png",
    slots9_9 : "/src/sprites/Symbols/icon10/wild10.png",
    slots9_10 : "/src/sprites/Symbols/icon10/wild11.png",
    slots9_11 : "/src/sprites/Symbols/icon10/wild12.png",
    slots9_12 : "/src/sprites/Symbols/icon10/wild13.png",
    slots9_13 : "/src/sprites/Symbols/icon10/wild14.png",
    slots9_14 : "/src/sprites/Symbols/icon10/wild15.png",
    slots9_15 : "/src/sprites/Symbols/icon10/wild16.png",

    slots10_0 : "/src/sprites/Symbols/icon11/Scatter1.png",
    slots10_1 : "/src/sprites/Symbols/icon11/Scatter2.png",
    slots10_2 : "/src/sprites/Symbols/icon11/Scatter3.png",
    slots10_3 : "/src/sprites/Symbols/icon11/Scatter4.png",
    slots10_4 : "/src/sprites/Symbols/icon11/Scatter5.png",
    slots10_5 : "/src/sprites/Symbols/icon11/Scatter6.png",
    slots10_6 : "/src/sprites/Symbols/icon11/Scatter7.png",
    slots10_7 : "/src/sprites/Symbols/icon11/Scatter8.png",
    slots10_8 : "/src/sprites/Symbols/icon11/Scatter9.png",
    slots10_9 : "/src/sprites/Symbols/icon11/Scatter10.png",
    slots10_10 : "/src/sprites/Symbols/icon11/Scatter11.png",
    slots10_11 : "/src/sprites/Symbols/icon11/Scatter12.png",
    slots10_12 : "/src/sprites/Symbols/icon11/Scatter13.png",
    slots10_13 : "/src/sprites/Symbols/icon11/Scatter14.png",
    slots10_14 : "/src/sprites/Symbols/icon11/Scatter15.png",
    slots10_15 : "/src/sprites/Symbols/icon11/Scatter16.png",

    megawinAnimBg: "src/sprites/rays.png",
    megawinStar: "src/sprites/stars.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/RobotoSlab-Bold.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.wav",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.wav",
        buttonpressed: "src/sounds/Game-Button.mp3",
 
};
